ALTER TABLE accounts ADD COLUMN name TEXT NOT NULL DEFAULT '';
ALTER TABLE accounts ADD COLUMN github_id TEXT;
ALTER TABLE accounts ADD COLUMN github_login TEXT;
CREATE UNIQUE INDEX accounts_github ON accounts(github_id) WHERE github_id IS NOT NULL;
CREATE TABLE sessions (token_hash TEXT PRIMARY KEY, account_id TEXT NOT NULL REFERENCES accounts(id), expires_at INTEGER NOT NULL);
CREATE INDEX sessions_expiry ON sessions(expires_at);
CREATE TABLE oauth_states (state_hash TEXT PRIMARY KEY, browser_hash TEXT NOT NULL, verifier TEXT NOT NULL, account_id TEXT REFERENCES accounts(id), expires_at INTEGER NOT NULL);
CREATE TABLE email_addresses (id TEXT PRIMARY KEY, account_id TEXT NOT NULL REFERENCES accounts(id), address TEXT NOT NULL, verified_at TEXT, token_hash TEXT, expires_at INTEGER, UNIQUE(account_id,address));
CREATE TABLE email_cooldowns (address_hash TEXT PRIMARY KEY, sent_at INTEGER NOT NULL);
ALTER TABLE endpoints ADD COLUMN delivery_mode TEXT NOT NULL DEFAULT 'webhook' CHECK(delivery_mode IN ('webhook','email','both'));
ALTER TABLE endpoints ADD COLUMN email_id TEXT REFERENCES email_addresses(id);
ALTER TABLE endpoints ADD COLUMN webhook_verified INTEGER NOT NULL DEFAULT 0;
UPDATE endpoints SET webhook_verified=1 WHERE status IN ('active','paused');
ALTER TABLE deliveries RENAME TO deliveries_v1;
DROP INDEX deliveries_due;
CREATE TABLE deliveries (id TEXT PRIMARY KEY, event_id TEXT NOT NULL REFERENCES events(id), endpoint_id TEXT NOT NULL REFERENCES endpoints(id), channel TEXT NOT NULL DEFAULT 'webhook' CHECK(channel IN ('webhook','email')), email_id TEXT REFERENCES email_addresses(id), status TEXT NOT NULL DEFAULT 'pending', attempts INTEGER NOT NULL DEFAULT 0, next_at INTEGER NOT NULL DEFAULT 0, lease TEXT, response_code INTEGER, error TEXT, provider_id TEXT, created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), UNIQUE(event_id,endpoint_id,channel));
INSERT INTO deliveries(id,event_id,endpoint_id,status,attempts,next_at,lease,response_code,error,created_at) SELECT id,event_id,endpoint_id,status,attempts,next_at,lease,response_code,error,created_at FROM deliveries_v1;
DROP TABLE deliveries_v1;
CREATE INDEX deliveries_due ON deliveries(status,next_at);
CREATE INDEX deliveries_endpoint ON deliveries(endpoint_id,created_at);
CREATE TABLE delivery_attempts (id TEXT PRIMARY KEY, delivery_id TEXT NOT NULL REFERENCES deliveries(id) ON DELETE CASCADE, attempt INTEGER NOT NULL, status TEXT NOT NULL, response_code INTEGER, error TEXT, created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')));
CREATE INDEX delivery_attempts_delivery ON delivery_attempts(delivery_id,attempt);
