ALTER TABLE accounts ADD COLUMN auth_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sessions ADD COLUMN auth_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sessions ADD COLUMN recovery_until INTEGER NOT NULL DEFAULT 0;
ALTER TABLE oauth_states ADD COLUMN auth_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE oauth_states ADD COLUMN purpose TEXT NOT NULL DEFAULT 'login';
